### ISSUE TITLE
Config is not automatically created

### ISSUE THREAD

**Issue by walkxcode** [notclickable-jordan/starbase-80#3]
Right now whenever you start the Docker container but haven't created a config, yet it will just crash.
![image](https://user-images.githubusercontent.com/71191962/233784707-f75b12a2-e85f-47f3-8a56-73c74fd89189.png)

It would be very nice to have it automatically generate a template config file for you. Or at least have some actual error catching. Maybe display an error message on the webpage instead of just stopping the entire container.

**Comment by viriatusX** [comment]
I'm with walkxcode.
There are plans to add Docker and Ping Status support?
Excellent work. Thanks

**Comment by notclickable-jordan** [comment]
With version 1.1.1 I fixed the issue of the site crashing if you forget to supply a config.json file. The builds also include amd64 and arm64 versions, so no more manual tagging.

I'm thinking about Docker and Ping status. That's how Ben Phelps' Homepage works, and I like his very much. It's a ways out, though, that's pretty complicated in terms of the Docker server talk. But if/once I can find some example code, I can wire up the React side pretty fast.

I was thinking a little orange dot next to a service if has issues. Otherwise it should look normal.

@viriatusX Please open a separate issue for Docker and Ping Status support, I'm closing this one.
