### ISSUE TITLE
[FEATURE REQUEST] Using the left side bar for server stats?

### ISSUE THREAD

**Issue by Sonny-Crockett** [notclickable-jordan/starbase-80#32]
Huge ST and LD fan so I love the aesthetic. Well done! 

I was thinking the negative space on the left side under the title would be a perfect spot for some server stats? I used glances and this unraid specific tool, but I'd understand making something more generic so it can accept more kinds of servers. 

[https://github.com/joweisberg/docker-glances](url)

[https://github.com/NebN/unraid-simple-monitoring-api](url)

What do you think? If you are keeping it blank to prevent clutter I totally get it.

**Comment by notclickable-jordan** [comment]
Thanks for the message, I'm a big Lower Decks fan too, obviously.

Unfortunately, though intentionally, the server code for Starbase 80 doesn't support this kind of functionality. It's a very simple static HTML site by design. No JavaScript.

Perhaps in the future I'll look to build Starbase 81 (or Douglas Station) and make something more complicated.
